futbol_end/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import index, region, reklama, malumotlar, post

urlpatterns = [
    path("", index, name="index"),
    path("region/<int:pk>/", region, name="region"),
    path("reklama/<int:pk>/", reklama, name="reklama"),
    path("malumotlar/", malumotlar, name="malumotlar"),
    path("post/", post, name="post")

]

clinet/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    photo = models.ImageField()

main/models.py
from django.db import models
from django.utils.translation import get_language

class TranslateHelperMixin:
    pass
    # def __getattr__(self, item):
    #     if item in self.translate_fields:
    #         lang = get_language()
    #         return getattr(self, '{}_{}'.format(item, lang))
    #
    #     return super(TranslateHelperMixin, self).__getattr__(item)



class Region(models.Model, TranslateHelperMixin):
    parent = models.ForeignKey('Region', on_delete=models.RESTRICT, null=True, default=None, blank=True)
    name_uz = models.CharField(max_length=250)
    name_ru = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name_uz


class District(models.Model):
    region = models.ForeignKey(Region, null=True, on_delete=models.SET_NULL)
    name_uz = models.CharField(max_length=250)
    name_ru = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name_uz


class Post(models.Model):
    region = models.ForeignKey(Region, null=True, on_delete=models.SET_NULL)
    district = models.ForeignKey(District, null=True, on_delete=models.SET_NULL)
    name_uz = models.CharField(max_length=250)
    name_ru = models.CharField(max_length=250)
    text_uz = models.TextField()
    text_ru = models.TextField()
    number = models.CharField(max_length=250)
    telegram = models.CharField(max_length=250)
    vaqt = models.CharField(max_length=250)
    price = models.PositiveIntegerField()
    img = models.ImageField(upload_to="images/")
    maydon_soni = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name_uz

clinet/views.py
from django.shortcuts import render
from clinet.models import User

main/views.py
from django.shortcuts import render, redirect
from main.models import *
from main.formas import *




def index(request):
    region = Region.objects.all()

    ctx = {
        "region": region
    }
    return render(request, "main/index.html", ctx)




def region(request, pk):
    tuman = District.objects.filter(region_id=pk)

    ctx = {
        "tuman": tuman
    }

    return render(request, "main/index.html", ctx)



def reklama(request, pk):
    post_re = Post.objects.filter(district_id=pk)

    ctx = {
        "post_re": post_re
    }
    return render(request, "main/region.html", ctx)



def malumotlar(request):
    malumot = Post.objects.all()
    cxt = {
        "malumot": malumot
    }

    return render(request, "main/barcha_post.html", cxt)



def post(request):
    model = Post()
    print(model)
    form = PostFrom(request.POST, request.FILES, instance=model)
    post_r = Region.objects.all()
    dic_r = District.objects.all()
    # print(form)
    if request.POST:
        if form.is_valid():
            print(form)
            form.save()
            return redirect('malumotlar')
        else:
            print(form.errors)
    ctx = {
        "form": form,
        "post_r": post_r,
        "dic_r": dic_r
    }
    return render(request, 'main/post.html', ctx)

templates/main/barcha_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Barcha Maydonlar</title>
    <link rel="stylesheet" href="{% static "css/Qashqadaryo.css" %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

</head>
<body style="margin-left: -182px;">


{% include "main/navbar.html" %}
<div class="container">
    <div class="row" style="margin-left: 400px;">
        {#                <div class="col-lg-8 order-lg-0 order-2">#}
        <div class="row">
            {% for i in malumot %}
                <div class="col-md-4 mb-4">
                    <img class="" style="height: 225px !important; width: 108% !important;"
                         src="{{ i.img.url }}"
                         alt="">
                </div>
                <div class="col-md-8 mb-4">
                    <div class="d-flex align-items-center">
                        <span class="bg-org">{{ i.region.name_uz }}</span>
                    </div>
                    <div>
                        <p class="text-capitalize fs5 my-3 fw-bolder">{{ i.name_uz }}</p>
                        <p class="text-muted">{{ i.text_uz }}</p>
                        <div class="d-flex justify-content-lg-start">
                            <div>
                                <p><b style="color: #0b2e13">Telefon:</b> <span
                                        style="color: #34ce57"><b>{{ i.number }}</b></span></p>
                            </div>
                            <p style="border: 1px solid red"></p>
                            <p><b style="color: #0b2e13; margin-left: 12px">Ish vaqti:</b> <span
                                    style="color: red; margin-left: 12px">{{ i.vaqt }}</span></p>
                            <p style="border: 1px solid red"></p>
                            <div style="width: 154px; margin-left: 12px">
                                <p><b style="color: black">Mydon soni</b>: <span
                                        style="color: #00cc00">{{ i.maydon_soni }}</span></p>
                            </div>
                            <p style="border: 1px solid red"></p>
                            <div style="width: 45px">
                                <p><b style="color: black; margin-left: 12px">Puli:</b> <span
                                        style="color: #20c997; margin-left: 12px">{{ i.price }}So'm</span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>
{#    </div>#}
{#</div>#}


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

</body>
</html>

templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sayt</title>
    <link rel="stylesheet" href="html/login-in.html">
    <link rel="stylesheet" href="{% static "css/new98.css" %}">
    <link rel="stylesheet" href="html/eder.html">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>
<body>
<nav style="width: 1367px;" class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">

        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Asosiy</a>
                </li>
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="html/login-in.html">Login</a>#}
{#                </li>#}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post' %}">Joylash</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'malumotlar' %}">E'lonlar</a>
                </li>
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"#}
{#                       data-toggle="dropdown" aria-expanded="false">#}
{#                        Uz#}
{#                    </a>#}
{#                    <div class="dropdown-menu dropdown-dark bg-dark" aria-labelledby="navbarDropdown ">#}
{#                        <a class="dropdown-item" href="#" style="color: white">Ru</a>#}
{#                    </div>#}
{#                </li>#}

            </ul>
        </div>

{#        <li class="nav-item dropdown nav-user">#}
{#            <a class="nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown"#}
{#               aria-haspopup="true" aria-expanded="false"><img src="{% static "img/WIN_20220519_15_21_05_Pro.jpg" %}"#}
{#                                                               alt="" class="user-avatar-md rounded-circle"></a>#}
{#            <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">#}
{#                <div class="nav-user-info">#}
{#                    <h6 class="mb-0 text-white nav-user-name">Jo'rayev Sherali</h6>#}
{#                    <span class="status"></span><span class="ml-2">O'zbekistan</span>#}
{#                </div>#}
{#                <a class="dropdown-item" href="#"><i class="fas fa-user mr-2"></i>Account</a>#}
{#                <a class="dropdown-item" href="#"><i class="fas fa-cog mr-2"></i>Setting</a>#}
{#                <a class="dropdown-item" href="#"><i class="fas fa-power-off mr-2"></i>Logout</a>#}
{#            </div>#}
{#        </li>#}
    </div>

</nav>

<div class="container">
    <div class="card">
        <div class="card-body">
            <p class="display-6 mb-3 fw-bolder">How it works</p>
            <p class="mb-0">No phone calls. No faxes. No navigating patient portals.</p>
            <p class="mb-0">PicinicHealth gather all of your medical records so you don't have to.</p>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Aloqa
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Murojat uchun malimot</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            ...
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary">Colos</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="allbox-1">
                <div class="box-1"></div>
                <div class="box-2"></div>
                <div class="box-6"></div>
            </div>
            <div class="allbox-9">
                <div class="box-1"></div>
                <div class="box-2"></div>
                <div class="box-6"></div>
            </div>
            <div class="allbox-14">
                <div class="box-1"></div>
                <div class="box-2"></div>
                <div class="box-6"></div>
            </div>
            <div class="allbox-2">
                <div class="box-1"></div>
                <div class="box-2"></div>
                <div class="box-4"></div>
            </div>
            <div class="allbox-3">
                <div class="box-1">

                </div>
                <div class="box-2">

                </div>
            </div>
            <div style="margin-top: 177px;" class="box-3"></div>
            <div class="box-4"></div>
            <div class="box-6"></div>
            <div class="box-4"></div>
        </div>
        <div class="card-footer">
            <div class="row mb-5">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-3">

                </div>
                <div class="col-lg-3">
                </div>
                <div class="col-lg-3">

                </div>
            </div>


            <div class="container mt-3 d-flex justify-content-center">
                <div class="dropdown_1">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" style="width: 29rem; background-color: #3bd63b;border-radius: 30px; "
                            aria-expanded="false">
                        <b>Viloyatni tanlash</b>
                    </button>
                    <div class="dropdown-menu" style="width: 29rem;" aria-labelledby="dropdownMenuButton">
                        {% for i in region %}
                            <a style="text-align: center" class="dropdown-item" href="{% url "region" i.pk %}">{{ i.name_uz }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>


            <div class="container mt-5 d-flex justify-content-center" style="margin-top: 170px">
                <div class="dropdown" style="margin-top: 150px">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-toggle="dropdown"
                            style="width: 29rem; background-color: #3bd63b; border-radius: 30px;margin-top: -80px;"
                            aria-expanded="false">
                        <b>Tumanlar tanlash</b>
                    </button>
                    <div class="dropdown-menu" style="width: 29rem" aria-labelledby="dropdownMenuButton">
                        {% for i in tuman %}
                            <a style="text-align: center" class="dropdown-item" style="width: 29rem"
                               href="{% url "reklama" i.pk %}">{{ i.name_uz }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>


            <div class="row mt-2">
                <div class="col-md-7">
                    <div class="d-flex flex-column">
                        <div class="mb-3">
                            <div>
                                <a class="btn btn-primary p-2 w-100 h-100 d-flex align-items-center justify-content-between"
                                   data-bs-toggle="collapse" href="#collapse1" role="button" aria-expanded="true"
                                   aria-controls="collapse1">
                                    <span>We're committed to public good research</span>
                                    <span class="fas fa-chevron-down"></span>
                                </a>
                            </div>
                            <div class="collapse show p-2 pt-0" id="collapse1">
                                <div class="">
                                    <p class="mb-0">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Atque
                                        nihil neque
                                        quisquam aut
                                        repellendus, dicta vero? Animi dicta cupiditate, facilis provident quibusdam
                                        ab
                                        quis,
                                        iste harum ipsum hic, nemo qui!
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, accusamus
                                        laudantium optio architecto obcaecati soluta impedit, ad ex veniam maiores
                                        dolorum blanditiis illum! Officia, similique sed natus asperiores
                                        exercitationem eius?</p>
                                </div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <div>
                                <a class="btn btn-primary p-2 w-100 h-100 d-flex align-items-center justify-content-between"
                                   data-bs-toggle="collapse" href="#collapse2" role="button" aria-expanded="true"
                                   aria-controls="collapse2">

                                    <span class="fas fa-chevron-down"></span>
                                </a>
                            </div>

                        </div>


                        <!--                        <div class="mb-3">-->
                        <!--                            <div>-->
                        <!--                                -->
                        <!--                                </a>-->
                        <!--                            </div>-->

                        <!--                        </div>-->
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="img-box">
                        <img style="height: 113%" class=""
                             src="{% static "img/sddefault.jpg" %}"
                             alt="">
                        <div class="box-1"></div>
                        <div class="box-2"></div>
                        <div class="box-3"></div>
                        <div class="box-5"></div>
                        <div class="box-6"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<footer style="margin-block-start: 37px;" id="footer">
    <div class="container">
        <div class="copyright"> &copy;  <strong><span>Code_Xn</span></strong>. 2022</div>
        <div class="credits">  <a href="#">Code_Xn</a></div>
    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>
</body>
</html>

templates/main/post.html
{#<form method="post" enctype="multipart/form-data" action="">#}
{#    {% csrf_token %}#}
{#    <tr>#}
{#        <th><label for="id_region">Region:</label></th>#}
{#        <br>#}
{#        <td>#}
{#            <select name="region" required id="id_region">#}
{#                <option value="" selected>---------</option>#}
{#                <option value="3">Qashqadoryo viloyati</option>#}
{#                <option value="4">Toshkent shahar</option>#}
{#                <option value="5">Xorazim viloyati</option>#}
{#            </select>#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_district">District:</label></th>#}
{#        <br>#}
{#        <td>#}
{#            <select name="district" required id="id_district">#}
{#                <option value="" selected>---------</option>#}
{#                <option value="1">Yakkabog&#x27; tumani</option>#}
{#                <option value="2">Koson tumani</option>#}
{#                <option value="3">Chorsu tumani</option>#}
{#            </select>#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_name_uz">Name uz:</label></th>#}
{#        <br>#}
{#        <td>#}
{#            <input type="text" name="name_uz" maxlength="250" required id="id_name_uz">#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_name_ru">Name ru:</label></th>#}
{#        <br>#}
{#        <td>#}
{#            <input type="text" name="name_ru" maxlength="250" required id="id_name_ru">#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_text_uz">Text uz:</label></th>#}
{#        <br>#}
{#        <td>#}
{#        <textarea name="text_uz" cols="40" rows="10" required id="id_text_uz"></textarea>#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_text_ru">Text ru:</label></th>#}
{#        <br>#}
{#        <td>#}
{#        <textarea name="text_ru" cols="40" rows="10" required id="id_text_ru"></textarea>#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_number">Number:</label></th>#}
{#        <br>#}
{#        <td>#}
{#            <input type="text" name="number" maxlength="250" required id="id_number">#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_telegram">Telegram:</label></th>#}
{#        <br>#}
{#        <td>#}
{#            <input type="text" name="telegram" maxlength="250" required id="id_telegram">#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_vaqt">Vaqt:</label></th>#}
{#        <br>#}
{#        <td>#}
{#            <input type="text" name="vaqt" maxlength="250" required id="id_vaqt">#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_price">Price:</label></th>#}
{#        <br>#}
{#        <td>#}
{#            <input type="number" name="price" min="0" required id="id_price">#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_img">Img:</label></th>#}
{#        <br>#}
{#        <td>#}
{#            <input type="file" name="img" accept="image/*" required id="id_img">#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <tr>#}
{#        <th><label for="id_maydon_soni">Maydon soni:</label></th>#}
{#        <br>#}
{#        <td>#}
{#            <input type="number" name="maydon_soni" required id="id_maydon_soni">#}
{#        </td>#}
{#    </tr>#}
{#    <br>#}
{#    <button type="submit"#}
{#            class="btn btn-block btn-dark btn-theme-colored btn-sm mt-20 pt-10 pb-10"#}
{#            data-loading-text="Please wait...">Saqlash#}
{#    </button>#}
{#</form>#}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Maydon joylash</title>
    <link rel="stylesheet" href="{% static "css/new98.css" %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>
<body>

<div class="row">
    <div class="col-4">
        {% include "main/navbar.html" %}
    </div>
    <div class="col-4 mt-4">
        <div class="container">
            <form>
                <div class="form-group">
                    <label for="id_region"><b>Viloyat tanlash</b></label>

                    <select class="form-control" name="district" id="id_district">
                        {% for i in post_r %}
                            <option>{{ i.name_uz }}</option>
                        {% endfor %}
                    </select>

                </div>

                <div class="form-group">
                    <label for="exampleFormControlSelect1"><b>Tuman tanlash</b></label>
                    <select class="form-control" name="district" required id="id_district">
                        {% for i in dic_r %}
                            <option>{{ i.name_uz }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1"><b>Maydon haqida</b></label>
                    <input type="text" class="form-control" name="name_uz" id="id_name_uz" aria-describedby="emailHelp">
                    <small id="emailHelp" class="form-text text-muted">...........</small>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlTextarea1"><b>Maydon haqida malumot</b></label>
                    <textarea class="form-control" id="id_text_uz" rows="3"></textarea>
                </div>


                <div class="form-group">
                    <label for="exampleInputEmail1"><b>Telefon raqam</b></label>
                    <input type="number" class="form-control" id="id_number" aria-describedby="emailHelp">
                    <small id="emailHelp" class="form-text text-muted">...........</small>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1"><b>Telegram username</b></label>
                    <input type="text" class="form-control" id="id_telegram" aria-describedby="emailHelp">
                    <small id="emailHelp" class="form-text text-muted">...........</small>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1"><b>Ish vaqti</b></label>
                    <input type="text" class="form-control" id="id_vaqt" aria-describedby="emailHelp">
                    <small id="emailHelp" class="form-text text-muted">...........</small>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1"><b>Maydon puli</b></label>
                    <input type="text" class="form-control" id="id_price" aria-describedby="emailHelp">
                    <small id="emailHelp" class="form-text text-muted">Maydon 1 soatlik vaqti</small>
                </div>


                <div class="form-group">
                    <label for="exampleFormControlFile1"><b>Maydon rasmi</b></label>
                    <input type="file" name="img" accept="image/*" required id="id_img">
                </div>


                <div class="form-group">
                    <label for="exampleInputEmail1"><b>Maydon soni</b></label>
                    <input type="number" class="form-control" id="id_maydon_soni" aria-describedby="emailHelp">
                </div>

                <button type="submit" class="btn btn-primary">Saqlash</button>
            </form>
        </div>
    </div>
</div>


<footer style="margin-block-start: 37px;" id="footer">
    <div class="container">
        <div class="row"></div>
        <div class="col-lg-6">
            <form action="" method="post"></form>
        </div>
    </div>
    </div> </div>
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 footer-links"><h4>Useful Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 footer-links"><h4>Our Services</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 footer-contact"><h4>Contact Us</h4>
                    <p> A108 Adam Street <br> New York, NY 535022<br> United States <br><br> <strong>Phone:</strong> +1
                        5589 55488 55<br> <strong>Email:</strong> info@example.com<br></p></div>
                <div class="col-lg-3 col-md-6 footer-info"><h3>About DevVE</h3>
                    <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita
                        valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
                    <div class="social-links mt-3"><a href="#" class="twitter"><i class="bx bxl-twitter"></i></a> <a
                            href="#" class="facebook"><i class="bx bxl-facebook"></i></a> <a href="#" class="instagram"><i
                            class="bx bxl-instagram"></i></a> <a href="#" class="linkedin"><i
                            class="bx bxl-linkedin"></i></a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright"> &copy; Copyright <strong><span>DevVE</span></strong>. All Rights Reserved</div>
        <div class="credits"> Designed by <a href="#">SalvadorDevVE</a></div>
    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

</body>
</html>